### PR TITLE
Update README: fixe lime link and download link.

### PR DESCRIPTION
**Pull request by ArnaudLigny**

### CODE REVIEW

**Comment by n1k0** [comment]
Thanks! I'm looking for transfering ownership of this repository, would you like to take over its development/maintainance? :)

**Comment by ArnaudLigny** [comment]
It smells like a trap, but OK, I'm interested to revive this project! :-)

**Comment by n1k0** [comment]
\o/ I'm making you the new owner right now. Thanks!

**Comment by n1k0** [comment]
Hmm, I got "Narno/phptwitterbot already exists". If you don't have modified things in your fork, trash it so I'll be able to transfer ownership :)

**Comment by ArnaudLigny** [comment]
Yes, cause of my patch (create a fork automatically). It's now deleted.

**Comment by n1k0** [comment]
Ownership transfer requested, you just got to approve it (think twice!) ;)

**Comment by ArnaudLigny** [comment]
It's done. Next step: Make robots compatible with the latest version of the Twitter API! :-)

**Pull request merged**
